version: '3.8'

services:
    app:
        build: .
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_DATABASE=todo_db
            - DB_USERNAME=root
            - DB_PASSWORD=root
        ports:
            - "8000:8000"
        command: php artisan serve --host=0.0.0.0 --port=8000  # Start Laravel

    db:
        image: mysql:5.7
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_db
        ports:
            - "3306:3306"

    testdb:
        image: mysql:5.7
        container_name: mysql_db_test
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_test
        ports:
            - "3307:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        depends_on:
            - db
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
