version: '3.8'
services:
    app:
        build: .
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_DATABASE=todo_db
            - DB_USERNAME=root
            - DB_PASSWORD=root
        ports:
            - "8000:8000"

    db:
        image: mysql:5.7
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_DATABASE: todo_db
            MYSQL_USER: root
            MYSQL_PASSWORD:
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        depends_on:
            - db
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
